@URL = 127.0.0.1
@PORT = 3001
### hi

### Service A Trigger.
POST http://{{URL}}:{{PORT}}/serviceA/start HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "domain": "ServiceA",
    "task": "processRT"
}

### Service A Activator.
POST http://{{URL}}:{{PORT}}/serviceA/activate HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "domain": "ServiceA",
    "task": "processRT",
    "taskType": "TRIGGER",
    "active": true
}

### Service B Trigger.
POST http://{{URL}}:{{PORT}}/serviceB/start HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "domain": "ServiceB",
    "task": "processRT"
}

### Service B Activator.
POST http://{{URL}}:{{PORT}}/serviceB/activate HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "domain": "ServiceB",
    "task": "processRT",
    "taskType": "TRIGGER",
    "active": true
}

### Service C Trigger.
POST http://{{URL}}:{{PORT}}/serviceC/start HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "domain": "ServiceC",
    "task": "processRT"
}

### Service C Activator.
POST http://{{URL}}:{{PORT}}/serviceC/activate HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "domain": "ServiceC",
    "task": "processRT",
    "taskType": "TRIGGER",
    "active": true
}

### Service C Helper Trigger.
POST http://{{URL}}:{{PORT}}/serviceC/start HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "domain": "ServiceC",
    "task": "processHelper"
}

### Service C Activator.
POST http://{{URL}}:{{PORT}}/serviceC/activate HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "domain": "ServiceC",
    "task": "processHelper",
    "taskType": "TRIGGER",
    "active": true
}

### Service D Trigger.
POST http://{{URL}}:{{PORT}}/serviceD/start HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "domain": "ServiceD",
    "task": "processRT"
}

### Service D Activator.
POST http://{{URL}}:{{PORT}}/serviceD/activate HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "domain": "ServiceD",
    "task": "processRT",
    "taskType": "TRIGGER",
    "active": true
}