@URL = 127.0.0.1
@PORT = 3007
### hi

### Service A Trigger.
POST http://{{URL}}:{{PORT}}/serviceA/start HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "domain": "ServiceA",
    "task": "processRT"
}

### Service A Activator.
POST http://{{URL}}:{{PORT}}/serviceA/activate HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "domain": "ServiceA",
    "task": "processRT",
    "taskType": "TRIGGER",
    "active": true
}