@URL = 127.0.0.1
@PORT = 3001


#####################################################
################## Controller test ##################
#####################################################

### A-first
POST http://{{URL}}:{{PORT}}/domain.a/service/processRT/start HTTP/1.1
 
### A-second
POST http://{{URL}}:{{PORT}}/domain.a/second-service/processRT/start HTTP/1.1

### D
POST http://{{URL}}:{{PORT}}/domain.d/service/processRT/start HTTP/1.1

#####################################################
#################### Query test #####################
#####################################################

### Histogram page에서 최근 Log 조회
GET http://{{URL}}:{{PORT}}/log/recent?domain=domain.a HTTP/1.1

### domain.a-service 조회
GET http://{{URL}}:{{PORT}}/log/recent?domain=domain.a&service=service HTTP/1.1

### domain.a-second-service 조회
GET http://{{URL}}:{{PORT}}/log/recent?domain=domain.a&service=second-service HTTP/1.1

### 특정 taskId 1개 전 꺼 조회
GET http://{{URL}}:{{PORT}}/log/recent?domain=domain.a&service=service&task=processRT HTTP/1.1

### 특정 taskId 2개 전 꺼 2page 조회
GET http://{{URL}}:{{PORT}}/log/recent?domain=domain.a&service=service&task=processRT&beforeCount=2&page=2 HTTP/1.1

### domainD, error 보기용
GET http://{{URL}}:{{PORT}}/log/recent?domain=domain.d&service=service&task=processRT&beforeCount=2&page=6 HTTP/1.1


### 특정 taskId 2개 전 꺼 3page 조회
GET http://{{URL}}:{{PORT}}/log/recent?domain=domain.a&service=service&task=processRT&beforeCount=2&page=3 HTTP/1.1



### Detail Log page에서 Log query

### taskId 전범위 검색

GET http://{{URL}}:{{PORT}}/log/taskid?&domain=domain.a&service=service&task=processRT&from=1710000000000&to=1711000000000 HTTP/1.1

### taskId 전범위 검색, level error
GET http://{{URL}}:{{PORT}}/log/taskid?&domain=domain.d&service=service&task=processRT&level=ERROR&from=1710000000000&to=1711000000000 HTTP/1.1

### taskId 전범위 검색, level error, warn
GET http://{{URL}}:{{PORT}}/log/taskid?&domain=domain.d&service=service&task=processRT&level=ERROR&level=WARN&from=1710000000000&to=1711000000000 HTTP/1.1

### taskId 전범위 검색, 특정 체인 2개, level error, warn
GET http://{{URL}}:{{PORT}}/log/taskid?&domain=domain.d&service=service&task=processRT&level=ERROR&level=WARN&chain=Chain_4830&chain=Chain_4765&from=1710000000000&to=1711000000000 HTTP/1.1

### taskId 전범위 검색, 특정 체인 2개, level error, warn (병렬처리)
GET http://{{URL}}:{{PORT}}/log/taskid/test?&domain=domain.d&service=service&task=processRT&level=ERROR&level=WARN&chain=Chain_4830&chain=Chain_4765&from=1710000000000&to=1711000000000 HTTP/1.1

### taskId 전범위 검색 특정 체인 1개
GET http://{{URL}}:{{PORT}}/log/taskid?&domain=domain.a&service=service&task=processRT&from=1710000000000&to=1711000000000&chain=Chain_16 HTTP/1.1



### taskId 전범위 검색 특정 체인 2개 포함 30번째 page
GET http://{{URL}}:{{PORT}}/log/taskid?&domain=domain.a&service=service&task=processRT&from=1710000000000&to=1711000000000&chain=Chain_16&chain=Chain_0&page=30 HTTP/1.1


### contextId 전범위 검색 1
GET http://{{URL}}:{{PORT}}/log/ctxid?&contextId=0t-ba3281ec-7f11-42df-b62d-8a78c54a8570&from=1710000000000&to=1711000000000 HTTP/1.1

### contextId 전범위 검색 2
GET http://{{URL}}:{{PORT}}/log/ctxid?&contextId=1234&from=1710000000000&to=1711000000000 HTTP/1.1


###

###

###

###

#####################################################
#################### Statistic test #################
#####################################################

### Graphmode graph 1개 조회
GET http://{{URL}}:{{PORT}}/stat/exe/taskid?domain=domain.a

### GRID Mode domain.a 조회 (24*7, 4h)

GET http://{{URL}}:{{PORT}}/stat/time/taskid?domain=domain.a&pointNumber=168&unitTime=4h

### GRID Mode domain.d 조회 (24*7, 24h)
GET http://{{URL}}:{{PORT}}/stat/time/taskid?domain=domain.d&pointNumber=168&unitTime=24h

### Histogram domain.a 조회 (30*10)

GET http://{{URL}}:{{PORT}}/stat/exe/taskid?domain=domain.a&pointNumber=30&pointSize=10

### Histogram domain.d 조회 (30*50)

GET http://{{URL}}:{{PORT}}/stat/exe/taskid?domain=domain.d&pointNumber=30&pointSize=50
